ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "15"

default_platform(:ios)

platform :ios do

  lane :test do
    scan(
      xcodebuild_command: "xcodebuild -disableAutomaticPackageResolution"
    )
  end

end